fairpolls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name= "polls"
urlpatterns = [
    path('',views.index, name="index"),
    path('<int:question_id>/',views.questionDetail, name="question_detail"),
    path('<int:question_id>/vote',views.vote, name="vote"),
    path('<int:question_id>/voted',views.votedSuccess, name="voted_success_page"),
    path('<int:question_id>/result',views.result, name="result"),
    path('login',views.loginView, name="login"),
]

polls/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Question(models.Model):
    name = models.CharField(max_length=200, null=True)
    pub_date =models.DateTimeField("date published", auto_now_add=True)
    closed_date = models.DateTimeField("Date closed")

    def __str__(self):
        return self.name
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=100, null=True)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Voter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    voter_id= models.CharField(max_length=40, null=True)
    email = models.EmailField(null=True)
    
    def __str__(self):
        return self.voter_id

class PollVote(models.Model):
    question = models.ForeignKey(Question, on_delete=models.SET_NULL, blank=True, null=True)
    choice = models.ForeignKey(Choice,on_delete=models.SET_NULL, blank=True, null=True)
    voter = models.ForeignKey(Voter, on_delete=models.SET_NULL, null=True, blank=True)
    time_voted = models.DateTimeField()

    def __str__(self):
        return self.question.name

polls/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreationUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1']

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import F
from django.utils import timezone
from .models import Voter,PollVote, Question, Choice
from .forms import CreationUserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required(login_url = "polls:login")
def index(request):
    question_list = Question.objects.all
    context = {
        "question_list": question_list
    }
    return render(request, "polls/index.html", context)

@login_required(login_url = "polls:login")
def questionDetail(request,question_id):
    question = Question.objects.get(pk=question_id)
    if question.closed_date < timezone.now():
        context = {
            "question":question,
            "message":"This poll is closed"
        }
        return render(request,"polls/question_detail.html", context)
    try:
        poll_voted_by_voter = PollVote.objects.get(question=question, voter=request.user.voter)
        print(poll_voted_by_voter)
        if poll_voted_by_voter:
            print("good")
        context = {
            "message":"You have already voted on this poll",
            "question":question
        }
        return render(request, "polls/question_detail.html", context)
    
    except(PollVote.DoesNotExist):
        print("in except clause")
        context = {
            "question": question
        }
        return render(request, "polls/question_detail.html", context)

@login_required(login_url = "polls:login")
def vote(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except(KeyError,Choice.DoesNotExist):
        context = {
            "question":question,
            "error_message": "You didn't select a choice"
        }
        return render(request, "polls/question_detail.html", context)
        return HttpResponseRedirect(reverse("polls:index"))
    selected_choice.votes = F("votes") + 1
    selected_choice.save()

    poll_voted = PollVote.objects.create(question=question,choice=selected_choice,
                    time_voted= timezone.now(), voter= request.user.voter)
    return HttpResponseRedirect(reverse("polls:voted_success_page", args=(question_id,)))

def votedSuccess(request, question_id):
    return render(request, "polls/succes_vote.html")

@login_required(login_url = "polls:login")
def result(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    highest_votes = 0
    choiceId = ""
    for choice in question.choice_set.all():
        votes = choice.votes
        if votes > highest_votes:
            highest_votes = votes
            choiceId = choice.id
    winner = Choice.objects.get(pk=choiceId)
    context = {
        "highest_votes":highest_votes,
        "winner":winner,
        "question":question
    }
    return render(request, "polls/result.html", context)

def loginView(request):
    form = CreationUserForm()
    context= {"form":form}

    if request.method == "POST":
        print(request.POST)
        voter_id = request.POST.get("voter_id")
        password = request.POST.get("password")
        user = authenticate(request, username=voter_id, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("polls:index"))
    return render(request, "polls/login.html", context)

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Polls Home</title>
</head>

<body>
    {% for question in question_list %}
    <a href="{% url 'polls:question_detail' question.id%}">{{question.name}}</a>
    {% endfor %}
</body>

</html>

polls/templates/polls/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>

<body>
    <!-- {{form.username}}
    {{form.password1}} -->
    <form method="POST" action="{% url 'polls:login' %}">
        {% csrf_token %}
        <input type="text" name="voter_id" id="voter_id" placeholder="Voter ID">
        <input type="password" name="password" id="password" placeholder="password">
        <input type="submit" value="Submit" name="login">
    </form>

</body>

</html>

polls/templates/polls/question_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vote on Poll</title>
</head>

<body>
    {% if message %}
    <p>{{message}}</p>
    <h1>{{question.name}}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{choice.name}}</li>
        {%endfor%}

    </ul>
    <a href="{% url 'polls:result' question.id %}">
        <p>See Results</p>
    </a>
    {% else %}
    <form method="POST" action="{% url 'polls:vote' question.id %}">
        {% csrf_token %}
        <h1>{{question.name}}</h1>
        <ul>
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" value="{{choice.id}}" id="choice{{forloop.counter}}">
            <label for="choice{{forloop.counter}}">{{choice.name}}</label>
            <br>
            {%endfor%}

        </ul>
        <input type="submit" value="Vote">
    </form>
    {% endif %}
    {% if error_message %}
    <p>{{error_message}}</p>
    {% endif %}

</body>

</html>

polls/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result</title>
</head>

<body>
    <h1>{{question.name}}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{choice.name}} || {{choice.votes}}</li>
        {%endfor%}
    </ul>

    <!-- <p>The winner is {{winner.name}}</p> -->
</body>

</html>

polls/templates/polls/succes_vote.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <p>You have successfully voted</p>
    <a href="{% url 'polls:index' %}">Go back to the home page</a>
</body>

</html>